imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: "@UserBundle/Resources/config/services.yml" }
    - { resource: "@CoreBundle/Resources/config/services.yml" }
    - { resource: "@FSerializerBundle/Resources/config/services.yml" }
    - { resource: "@ConversationBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # http://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id:  session.handler.native_file
        save_path:   "/usr/share/fsddev-app/sessions/%kernel.environment%"
    fragments:       ~
    http_method_override: true
    assets: ~

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            gedmo_tree:
                type: annotation
                prefix: Gedmo\Tree\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                alias: GedmoTree # this one is optional and will default to the name set for the mapping
                is_bundle: false

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


######### ADDITIONALS CONFIG ##########
fos_user:
    service:
            mailer: fos_user.mailer.twig_swift
    resetting:
      token_ttl: 300
      email:
        from_email:
          address:        agent-resetting@tcr.com
          sender_name:    Agent Resetting
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: UserBundle\Entity\Agent

assetic:
    bundles:
      - CoreBundle
    assets:
      symfony_helpers:
        output: '../EmberApp/vendor/bundles/core/js/api-codes.js'
        filter: uglifyjs2
        inputs:
          - 'js/api-codes.js'
      symfony_translation:
        output: '../EmberApp/vendor/bundles/bazingajstranslation/main.js'
        filter: uglifyjs2
        inputs:
          - 'bundles/bazingajstranslation/js/translator.min.js'
          - 'js/translations/config.js'
          - 'js/translations/*/*.js'
      symfony_routes:
        output: '../EmberApp/vendor/bundles/fosjsrouting/main.js'
        filter: uglifyjs2
        inputs:
          - 'bundles/fosjsrouting/js/router.js'
          - 'js/fos_js_routes.js'

    node: /usr/bin/nodejs
    filters:
      uglifycss:
        bin: /usr/local/lib/npm/bin/uglifycss
      uglifyjs2:
        bin:  /usr/local/lib/npm/bin/uglifyjs

bazinga_js_translation:
    locale_fallback:      en

fos_oauth_server:
    db_driver: orm
    client_class:        UserBundle\Entity\Client
    access_token_class:  UserBundle\Entity\AccessToken
    refresh_token_class: UserBundle\Entity\RefreshToken
    auth_code_class:     UserBundle\Entity\AuthCode
    service:
        user_provider: agent.oauth.username_email.user.provider
        options:
          access_token_lifetime: 60
          refresh_token_lifetime: 1209600

stof_doctrine_extensions:
    default_locale: "%locale%"
    orm:
        default:
            tree: true