security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
#        api:
#            pattern:    ^/api
#            fos_oauth:  true
#            stateless:  true
#            anonymous: true

#        main:
#            pattern: ^/
#            form_login:
#                provider: fos_userbundle
#            logout:       true
#            anonymous:    true

        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            anonymous: true

    access_control:
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN