services:
    agent_system.payment_info.repository:
        class: PaymentBundle\Business\Repository\PaymentInfoRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - PaymentBundle\Entity\PaymentInfo

    agent_system.payment_info.manager:
        class: PaymentBundle\Business\Manager\PaymentInfoManager
        arguments:
            repository: "@agent_system.payment_info.repository"
            agentManager: "@agent_system.agent.manager"
            fSerializer: "@f_serializer"
            commissionManager: "@agent_system.commission.manager"
            tokenStorrage:   "@security.token_storage"

    agent_system.payment_info.adapter:
            class: PaymentBundle\Adapter\PaymentInfo\PaymentInfoAdapter
            arguments:
                - "@agent_system.payment_info.manager"
            tags:
                - { name: request.param_converter, converter:attribute priority: 10 }

    agent.system.pdf.generator:
            class:  PaymentBundle\Business\Manager\PDFGenerator
