services:

     # ------ Image --------------------------------------------------------------------------------------------------- #
    agent_system.image_repository:
        class: UserBundle\Business\Repository\ImageRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - UserBundle\Entity\Document\Image

    agent_system.image_manager:
       class: UserBundle\Business\Manager\ImageManager
       arguments:
             repository: "@agent_system.image_repository"

    agent_system.image.adapter:
        class: UserBundle\Adapter\Image\ImageAdapter
        arguments:
            - "@agent_system.image_manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }

     # ------ File --------------------------------------------------------------------------------------------------- #
    agent_system.file_repository:
        class: UserBundle\Business\Repository\FileRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - UserBundle\Entity\Document\Image

    agent_system.file_manager:
       class: UserBundle\Business\Manager\FileManager
       arguments:
             repository: "@agent_system.file_repository"

 # ------ Address --------------------------------------------------------------------------------------------------- #
    agent_system.address_repository:
        class: UserBundle\Business\Repository\AddressRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - UserBundle\Entity\Address

    agent_system.address_manager:
       class: UserBundle\Business\Manager\AddressManager
       arguments:
             repository: "@agent_system.address_repository"

    agent_system.address.adapter:
        class: UserBundle\Adapter\Address\AddressAdapter
        arguments:
            - "@agent_system.address_manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }


    # ------ Group --------------------------------------------------------------------------------------------------- #
    agent_system.group.repository:
        class: UserBundle\Business\Repository\GroupRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - UserBundle\Entity\Group

    agent_system.group.manager:
        class: UserBundle\Business\Manager\GroupManager
        arguments:
            repository: "@agent_system.group.repository"
            fSerializer: "@f_serializer"

    agent_system.group.adapter:
        class: UserBundle\Adapter\Group\GroupAdapter
        arguments:
            - "@agent_system.group.manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }

    # ------ Role ---------------------------------------------------------------------------------------------------- #
    agent_system.role.repository:
        class: UserBundle\Business\Repository\RoleRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - UserBundle\Entity\Role

    agent_system.role.manager:
        class: UserBundle\Business\Manager\RoleManager
        arguments:
            repository: "@agent_system.role.repository"
            fSerializer: "@f_serializer"

    agent_system.role.adapter:
        class: UserBundle\Adapter\Role\RoleAdapter
        arguments:
            - "@agent_system.role.manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }

    fos_oauth_server.controller.token:
            class: UserBundle\Controller\TokenController
            arguments: ['@fos_oauth_server.server', '@doctrine.orm.entity_manager', '@fos_user.user_manager', '@fos_oauth_server.storage']

    # ------ TCR User ------------------------------------------------------------------------------------------------ #
    agent_system.tcr_user_manager:
        class: UserBundle\Business\Manager\TCRUserManager
        arguments:
            fSerializer: "@f_serializer"
            tokenStorage: '@security.token_storage'
            agentManager: '@agent_system.agent.manager'

    agent_system.tcr_user.adapter:
        class: UserBundle\Adapter\TCRUser\TCRUserAdapter
        arguments:
            - "@agent_system.tcr_user_manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }

    # ------ Agent --------------------------------------------------------------------------------------------------- #
    agent_system.agent.repository:
        class: UserBundle\Business\Repository\AgentRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - UserBundle\Entity\Agent

    agent_system.agent.manager:
        class: UserBundle\Business\Manager\AgentManager
        arguments:
            repository:  "@agent_system.agent.repository"
            roleManager: "@agent_system.group.manager"
            fSerializer: "@f_serializer"

    agent_system.agent.adapter:
        class: UserBundle\Adapter\Agent\AgentAdapter
        arguments:
            - "@agent_system.agent.manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }

    agent.oauth.username_email.user.provider:
        class: UserBundle\Business\Provider\AgentOauthProvider
        arguments:
                    - "@agent_system.agent.manager"

    # ------ Invitation ---------------------------------------------------------------------------------------------- #
    agent_system.invitation.repository:
        class: UserBundle\Business\Repository\InvitationRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - UserBundle\Entity\Invitation

    agent_system.invitation.manager:
        class: UserBundle\Business\Manager\InvitationManager
        arguments:
            repository: "@agent_system.invitation.repository"
            fSerializer: "@f_serializer"

    agent_system.invitation.adapter:
        class: UserBundle\Adapter\Invitation\InvitationAdapter
        arguments:
            - "@agent_system.invitation.manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }
