services:
    # ------ Message ------------------------------------------------------------------------------------------------- #
    agent_system.message.repository:
        class: ConversationBundle\Business\Repository\MessageRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - ConversationBundle\Entity\Message

    agent_system.message.manager:
        class: ConversationBundle\Business\Manager\MessageManager
        arguments:
            repository: "@agent_system.message.repository"
            fSerializer: "@f_serializer"
            messageComposer: "@fos_message.composer.default"
            messageSender: "@fos_message.sender.default"
            eventDispatcher: "@event_dispatcher"

    agent_system.message.adapter:
        class: ConversationBundle\Adapter\Message\MessageAdapter
        arguments:
            - "@agent_system.message.manager"
        tags:
            - { name: request.param_converter, converter:attribute priority: 10 }